version: '3.4'

services:

  payment_ms:
    build:
      context: .
      dockerfile: Dockerfile
    image: payment_ms
    env_file: .env
    ports:
      - '8080:8080'

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_ROOT_USER}
      - POSTGRES_PASSWORD=${POSTGRES_ROOT_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - data:/data/db

  adminer:
    image: adminer
    restart: always
    ports:
      - '8081:8080'

volumes:
  data: