version: '3.4'

services:

    payment_ms:
        build:
            context: .
            dockerfile: Dockerfile
        image: crowstream_payment_ms
        container_name: crowstream_payment_ms
        depends_on:
            - payment_db
        environment:
            - PAYMENT_DB_URL=${PAYMENT_DB_URL}
            - PAYMENT_DB_USER=${PAYMENT_DB_USER}
            - PAYMENT_DB_PASSWORD=${PAYMENT_DB_PASSWORD}
        ports:
            - '8080:8080'

    payment_db:
        image: postgres:14.1
        container_name: crowstream_payment_db
        environment:
            - POSTGRES_USER=${PAYMENT_DB_USER}
            - POSTGRES_PASSWORD=${PAYMENT_DB_PASSWORD}
            - POSTGRES_DB=${PAYMENT_DB_DATABASE}
        ports:
            - '5432:5432'
        volumes:
            - payment_data:/data/db

    pgadmin:
        image: dpage/pgadmin4
        restart: always
        container_name: crowstream_pgadmin4
        depends_on:
            - payment_db
        environment:
            - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
            - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
        ports:
            - '8045:80'

volumes:
    payment_data: